FROM node:20 as build

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 복사
COPY . .

# 환경변수 세팅 

ARG SERVER_DOMAIN
ARG SERVER_PORT

RUN echo "REACT_APP_SERVER_ADDRESS=https://${SERVER_DOMAIN}:${SERVER_PORT}/api" > .env


# 애플리케이션 빌드
RUN npm run build

# 2. 배포 스테이지
FROM nginx:alpine


# 빌드된 파일을 Nginx html 디렉토리로 복사
COPY --from=build /app/build /usr/share/nginx/html

# Nginx 실행 명령 
CMD ["nginx", "-g", "daemon off;"]
