# 1. 빌드 스테이지
FROM node:lts-alpine AS build-stage

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 소스 복사
COPY . .

# 애플리케이션 빌드
RUN npm run build

# 2. 배포 스테이지
FROM nginx:alpine AS production-stage

# 기본 Nginx 설정 파일 제거
RUN rm -rf /etc/nginx/conf.d/default.conf

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 빌드된 파일을 Nginx html 디렉토리로 복사
COPY --from=build-stage /app/build /usr/share/nginx/html

# Nginx 포트 설정
EXPOSE 80

# Nginx 실행 명령
CMD ["nginx", "-g", "daemon off;"]
